### ISSUE TITLE
Command should use $io to show info instead of flash messages

### ISSUE THREAD

**Issue by georgringer** [smichaelsen/melon-images#60]
The command `CreateNeededCroppings` does currently generate a flash message which is not used when using the command via CLI. As I didn't know the intentions I left it like it is.

Proposal: If CLI call I would use `$io` to show the info to the user and just use the flash message if called via backend

**Comment by smichaelsen** [comment]
Fixed with https://github.com/smichaelsen/melon-images/commit/ac938a6de746af353b5b24549d2458abc30309d3
